### ISSUE TITLE
"Cannot find module './plugin-manager'"

### ISSUE THREAD

**Issue by ambarusa** [atom-haskell/language-haskell#106]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: 'ide-haskell' package vundefined

### Stack Trace

Failed to activate the ide-haskell package

```
At Cannot find module './plugin-manager'

Error: Cannot find module './plugin-manager'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.17.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.17.0/resources/app/src/module-cache.js:354:1)
    at Module.require (~/AppData/Local/atom/app-1.17.0/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.17.0/resources/app/src/native-compile-cache.js:66:1)
    at Object.activate (/packages/ide-haskell/lib/ide-haskell.coffee:170:23)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.17.0/resources/app/src/package.js:253:1)
    at ~/AppData/Local/atom/app-1.17.0/resources/app/src/package.js:1014:1
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at PackageManager.module.exports.PackageManager.triggerActivationHook (~/AppData/Local/atom/app-1.17.0/resources/app/src/package-manager.js:686:1)
    at Workspace.handleGrammarUsed (~/AppData/Local/atom/app-1.17.0/resources/app/src/workspace.js:1337:1)
    at TextEditor.module.exports.TextEditor.observeGrammar (~/AppData/Local/atom/app-1.17.0/resources/app/src/text-editor.js:628:1)
    at ~/AppData/Local/atom/app-1.17.0/resources/app/src/workspace.js:571:1
    at ~/AppData/Local/atom/app-1.17.0/resources/app/src/workspace.js:576:1
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at PaneContainer.didAddPaneItem (~/AppData/Local/atom/app-1.17.0/resources/app/src/pane-container.js:266:1)
    at Pane.module.exports.Pane.addItem (~/AppData/Local/atom/app-1.17.0/resources/app/src/pane.js:532:1)
    at Pane.module.exports.Pane.activateItem (~/AppData/Local/atom/app-1.17.0/resources/app/src/pane.js:468:1)
    at Workspace.<anonymous> (~/AppData/Local/atom/app-1.17.0/resources/app/src/workspace.js:1111:1)
    at next (<anonymous>)
    at step (~/AppData/Local/atom/app-1.17.0/resources/app/src/workspace.js:11:1)
```

### Commands

```
  5x -9:40.7.0 core:save (input.hidden-input)
     -8:12.1.0 core:backspace (input.hidden-input)
     -8:11.2.0 core:save (input.hidden-input)
     -7:13.6.0 core:confirm (input.hidden-input)
     -6:57.8.0 core:backspace (input.hidden-input)
  3x -3:41.3.0 application:open-file (div.panels-item)
```

### Non-Core Packages

```
atom-beautify 0.29.24 
language-haskell 1.12.1 
minimap 4.28.2 
Sublime-Style-Column-Selection 1.7.4 
```

**Comment by lierdakil** [comment]
This isn't the right repo, but whatever. Uninstall, then reinstall ide-haskell, something broke during installation. It happens with Atom from time to time.
