### ISSUE TITLE
Installing “language-haskell@1.7.14” failed.

### ISSUE THREAD

**Issue by Kaiochao** [atom-haskell/language-haskell#74]
Under "Install Packages", installing this package fails with the output: 

```
Installing “language-haskell@1.7.14” failed.

> language-haskell@1.7.14 postinstall C:\Users\Davidson\AppData\Local\Temp\apm-install-dir-11644-15308-tids92\node_modules\language-haskell
> node ./node_modules/.bin/coffee src/haskell.coffee



C:\Users\Davidson\AppData\Local\Temp\apm-install-dir-11644-15308-tids92\node_modules\language-haskell\node_modules\.bin\coffee:2
basedir=`dirname "$0"`
        ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Davidson\\AppData\\Local\\atom\\app-1.7.3\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Davidson\\AppData\\Local\\atom\\app-1.7.3\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Davidson\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Davidson\\.atom\\.apmrc" "install" "C:\\Users\\Davidson\\AppData\\Local\\Temp\\d-11644-15308-1xn95ac\\package.tgz" "--target=0.36.8" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! language-haskell@1.7.14 postinstall: `node ./node_modules/.bin/coffee src/haskell.coffee`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the language-haskell@1.7.14 postinstall script 'node ./node_modules/.bin/coffee src/haskell.coffee'.
npm ERR! This is most likely a problem with the language-haskell package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/.bin/coffee src/haskell.coffee
npm ERR! You can get their info via:
npm ERR!     npm owner ls language-haskell
npm ERR! There is likely additional logging output above.
```

**Comment by lierdakil** [comment]
What the hell, Windows?

Please try 1.7.15.

**Comment by Kaiochao** [comment]
Works, thanks.
